FROM python:3.9-slim

# Set working directory - 
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY task_queue/ ./task_queue/
COPY task_workers/ ./task_workers/

# Set Python path
ENV PYTHONPATH=/app

# Run worker
CMD ["python", "task_workers/worker.py", "Worker-Docker"]